---

- src: https://github.com/Ollrins/ClickHouse-role.git
  version: "1.13"
  name: clickhouse

- src: https://github.com/Ollrins/Vector-role.git
  version: "1.0.0"
  name: vector
             
- src: https://github.com/Ollrins/Lighthouse-role.git
  version: "1.0.0"
  name: lighthouse
